server:
  port: 80
redis:
    host: localhost
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 3000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

#wechat
wechat:
    appid: wx2bfe10856c232ba3
    appsecret: 38f855811be7b851e45bb92835301a9d
    token:
    auth:
       get-access-token-url: https://api.weixin.qq.com/cgi-bin/

spring:
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths: src/main/java #生效的位置设定